[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
looties_contract = "t1ynC7jhTJfZD8idR58Yz6EW8XiwajKzNXusf2tguBV"

[programs.devnet]
looties_contract = "t1ynC7jhTJfZD8idR58Yz6EW8XiwajKzNXusf2tguBV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
